-- 코드를 입력하세요
SELECT HISTORY_ID, CAR_ID,DATE_FORMAT("0000-00-00",START_DATE) AS START_DATE,
DATE_FORMAT("0000-00-00",END_DATE) AS END_DATE,
IF(DATEDIFF(END_DATE,START_DATE)>=29,"장기 대여","단기 대여") AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE("2022-09%")
ORDER BY HISTORY_ID DESC